version: "3.8"
services:
  site:
    command: jekyll serve --livereload
    image: jekyll/jekyll:latest
    volumes:
      - .:/srv/jekyll
      - .:/usr/local/bundle
    ports:
      - 4000:4000
  build:
    command: jekyll build
    image: jekyll/jekyll:latest
    volumes:
      - .:/srv/jekyll      
      - .:/usr/local/bundle